app/posts/forms.py
from wtforms import Form, StringField, TextAreaField
from wtforms.validators import InputRequired, Email

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

# Я сделал проверку на условие title = ""
# можно сделать так было, воспользоваться стандартным валидатором wtforms
    # title = StringField('Title',[validators.Length(min=5, max=40)])
    # body = TextAreaField('Body',[validators.Length(min=5, max=10000)])


# class BaseUserForm(Form):
#     name = StringField('Name')
#     email = TextAreaField('Email')

app/posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import db
from models import Post, Tag
from .forms import PostForm
from flask_security import login_required


posts = Blueprint('posts', __name__,
                   template_folder='templates')

@posts.route('/create', methods=["POST", "GET"])
@login_required
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            if post.title == "":
                 return redirect(url_for('posts.create_post'))
            else:
                db.session.add(post)
                db.session.commit()
        except:
            print('Text wrong')

        return redirect( url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST','GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) 
    else:
        posts = Post.query.order_by(Post.created.desc())

    #Не работает пагинация в поиске, вместо нее вывод всех постов
    # if q:
    #     posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) 
    #     pages = posts.paginate(page=page, per_page=len(posts.all()))
    # else:
    #     posts = Post.query.order_by(Post.created.desc())
    #     pages = posts.paginate(page=page, per_page=5)
    
    pages = posts.paginate(page=page, per_page=5)
    
    return render_template('posts/index.html', pages=pages, q=q)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tags_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form  %}
                <div class="form-group">
                    {{ field.label(class="form-label") }}
                    {{ field(class="form-control", rows="5") }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}


{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form  %}
                <div class="form-group">
                    {{ field.label(class="form-label") }}
                    {{ field(class="form-control", rows="5") }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </div>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}


{% block title %}
    Blueprint Title
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}



{% for post in pages.items %}
<p>
    <a href= "{{  url_for('posts.post_detail', slug=post.slug) }}"> {{ post.title }} </a>
</p>
{%endfor%}

{% if q %}
    {% set q='&q=%s' % q %}

    <nav aria-label="...">
        <ul class="pagination">
        <li {% if not pages.has_prev %}
                    class="disabled page-item"
                {% else%}
                    class="page-item"    
                {%endif%}>

                <a class="page-link" href="./?page={{ pages.prev_num }}{{q}}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for page in pages.iter_pages() %}
            <li aria-current="page"
                {% if page == pages.page %} 
                    class="page-item active" 
                {% else %}   
                    class="page-item" 
                {% endif %}>
                    <a class="page-link" href="./?page={{ page }}{{q}}">{{ page }}</a>
            </li>
        {%endfor%}
        
        
        <li {% if not pages.has_next %}
                class="disabled page-item"
            {% else%}
                class="page-item"    
            {%endif%}>
            <a class="page-link" href="./?page={{ pages.next_num }}{{q}}">Next</a>
        </li>
        </ul>
    </nav>
{% else %}
    <nav aria-label="...">
        <ul class="pagination">
        <li {% if not pages.has_prev %}
                    class="disabled page-item"
                {% else%}
                    class="page-item"    
                {%endif%}>

                <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for page in pages.iter_pages() %}
            <li aria-current="page"
                {% if page == pages.page %} 
                    class="page-item active" 
                {% else %}   
                    class="page-item" 
                {% endif %}>
                    <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
        {%endfor%}
        
        
        <li {% if not pages.has_next %}
                class="disabled page-item"
            {% else%}
                class="page-item"    
            {%endif%}>
            <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
        </li>
        </ul>
    </nav>
{% endif %}
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}

    <div class="main-content">
        {{ post.body }}
    </div> 
    <div class="tags">
        {% for tag in tags%}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="badge text-bg-primary">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>  
{% endblock %}

app/posts/templates/posts/tags_detail.html
{% extends 'base.html' %}


{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag
{% endblock %}

{% block content %}
    
        {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ tag.name }}</a>
        </div>
        {% endfor %}
      
{% endblock %}